#!/bin/bash

# ---------------------------
#
# Common settings for all contexts, base for development.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------
export MLKC_POBLACION_APP_NAME=context_data

# -----
# dev cell_raw_data PostGIS
# -----
export MLKC_POBLACION_NETWORK=cell_raw_data
export MLKC_POBLACION_HOST=cell_raw_data
export MLKC_POBLACION_PG_EXTERNAL_PORT=5432
export MLKC_POBLACION_POSTGIS_USER=postgres
export MLKC_POBLACION_POSTGIS_PASSWORD=postgres
export MLKC_POBLACION_DB=cell_raw_data
